version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3.13-management-alpine"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  email-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASS: "guest"
      AMQP_QUEUE_NAME: "apex"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
