version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3.13-management-alpine"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  email-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASS: "guest"
    env_file:
      - .env
    depends_on:
      - rabbitmq
